### PR TITLE
accept channelConfig argument for simple-peer. update README.

### PR DESCRIPTION
**Pull request by mreinstein**

### CODE REVIEW

**Comment by mreinstein** [comment]
resolves #16

**Comment by perguth** [comment]
🚀 Nice!

Please merge my [revision](https://github.com/mreinstein/webrtc-swarm/pull/1), then I am on go for a merge.

**Comment by perguth** [comment]
Thanks! 💯 

@mafintosh, I guess we should bump a minor :-)

**Comment by mafintosh** [comment]
woot. 2.8.0

**Pull request merged**
